# Generated by Django 5.2.6 on 2025-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='account_name',
            new_name='reference_no',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='card_holder',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='hash_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='swift_code',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='year',
        ),
        migrations.AddField(
            model_name='transactions',
            name='receipt_upload',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
