# Generated by Django 5.2.6 on 2025-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_account_name_transactions_reference_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_methods',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
