# Generated by Django 5.2.6 on 2025-09-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactions_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='reference_no',
        ),
    ]
