# Generated by Django 5.2.6 on 2025-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_transactions_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAW', 'WITHDRAW'), ('INVESTMENT', 'INVESTMENT'), ('ROI', 'ROI')], max_length=200),
        ),
    ]
